name: Deploy production
on:
  pull_request:
    types:
      - closed
    branches:
      - "main"
jobs:
  deploy:
    name: Deploy producao
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy Files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 21
          local-dir: "./"
          server-dir: "./api.sankhya.sync.brasilcentral/"
          git-ftp-args: "--changed-only"
      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/group-apis/api.sankhya.sync.brasilcentral
            yarn
            yarn prisma generate
